Update E9Syscall ready for public release

diff --git a/e9syscall b/e9syscall
--- a/e9syscall
+++ b/e9syscall
@@ -67,41 +67,23 @@ HOOKNAME=`basename "$HOOK" .c`
 
 set -e
 
-# STEP (1): install e9patch if necessary:
+# STEP (1): check if e9patch is installed:
 if [ ! -x ./e9patch ]
 then
-    if [ ! -f e9patch-master.zip ]
-    then
-        echo -e "${GREEN}$0${OFF}: downloading e9patch-master.zip..."
-        wget -O e9patch-master.zip https://github.com/GJDuck/e9patch/archive/master.zip
-    fi
-
-    echo -e "${GREEN}$0${OFF}: extracting e9patch-master.zip..."
-    unzip e9patch-master.zip
-
-    echo -e "${GREEN}$0${OFF}: building e9patch..."
-    cd e9patch-master
-    ./build.sh
-    cd ..
-    ln -f -s e9patch-master/e9patch
-    ln -f -s e9patch-master/e9tool
-    ln -f -s e9patch-master/e9compile.sh
-    echo -e "${GREEN}$0${OFF}: e9patch has been built..."
-else
-	echo -e "${GREEN}$0${OFF}: using existing e9patch..."
+    echo -e "${RED}error${OFF}: e9patch is not installed (run ./build.sh first) " >&2
 fi
 
 # STEP (2): build the hook code:
 echo -e "${GREEN}$0${OFF}: building hook ($HOOK)..."
-./e9compile.sh e9syscall.c -O2 -Werror -include "$HOOK" -I "$PWD"
-mv e9syscall "e9syscall_$HOOKNAME"
+./e9compile.sh e9syscall-rt.c -O2 -Werror -include "$HOOK" -I "$PWD"
+mv e9syscall-rt "e9syscall_hook_$HOOKNAME"
 
 # STEP (3): patch libc:
 echo -e "${GREEN}$0${OFF}: patching libc ($LIBC)..."
-echo "./e9tool --match 'asm=syscall' --action 'call[conditional] intercept(&rax,rdi,rsi,rdx,r10,r8,r9)@'"e9syscall_$HOOKNAME" "$LIBC" -o "libc-$HOOKNAME.so""
+echo "./e9tool --match 'asm=syscall' --action 'call[conditional] intercept(&rax,rdi,rsi,rdx,r10,r8,r9)@'"e9syscall_hook_$HOOKNAME" "$LIBC" -o "libc-$HOOKNAME.so""
 ./e9tool \
     --match  'asm=syscall' \
-    --action 'call[conditional] intercept(&rax,rdi,rsi,rdx,r10,r8,r9)@'"e9syscall_$HOOKNAME" \
+    --action 'call[conditional] intercept(&rax,rdi,rsi,rdx,r10,r8,r9)@'"e9syscall_hook_$HOOKNAME" \
     "$LIBC" -o "libc-$HOOKNAME.so" | tee "e9patch-$HOOKNAME.log"
 
 echo -e "${GREEN}$0${OFF}: done!"
